/**
 * Differential test against the original Python.
 *
 * The fixture is generated by executing the real warehouse_smoke_layer.py from
 * Dropbox (07 Technical Tools/1. Internal/Base Warehouse Smoke Depth) — its own
 * loop text, with only the input assignments substituted — so this compares the
 * port against the author's arithmetic rather than against a transcription of
 * it. Regenerate with fixtures/generate_oracle.py.
 *
 * Every timestep of every series is compared, not a sample. Ten cases span the
 * regimes: never breached, prompt ASET, heavy racking, low headroom, the 900 K
 * plume cap, and unit / sub-second / coarse timesteps.
 */
import { readFileSync } from 'fs';
import { join } from 'path';
import { gunzipSync } from 'zlib';

import { calculateSmokeLayer } from '@/lib/smoke-layer-calc';
import type { SmokeLayerInputs, SmokeLayerStep } from '@/lib/smoke-layer-types';

const FIXTURE =
  process.env.ORACLE_JSON ?? join(__dirname, 'fixtures', 'python-oracle.json.gz');

type PythonCase = {
  rset: number;
  aset: number;
  asetTriggered: boolean;
  breachTime: number | null;
  referenceHeightBreached: boolean;
  finalClearHeight: number;
  totalPreEvac: number;
  peoplePerSecond: number;
  queueTime: number;
  stepCount: number;
  steps: Record<string, number[]>;
};

type Fixture = {
  cases: Record<string, PythonCase>;
  inputs: Record<string, Record<string, number>>;
};

function load(path: string): Fixture {
  const raw = readFileSync(path);
  return JSON.parse((path.endsWith('.gz') ? gunzipSync(raw) : raw).toString('utf-8'));
}

const fixture: Fixture = load(FIXTURE);
const caseNames = Object.keys(fixture.cases);

/** snake_case inputs as the Python script names them -> the TS input object. */
function toInputs(py: Record<string, number>): SmokeLayerInputs {
  return {
    roomArea: py.room_area,
    rackingPerc: py.racking_perc,
    roomHeight: py.room_height,
    fgr: py.fgr,
    detectionTime: py.detection_time,
    preMovementTime: py.pre_movement_time,
    maximumTravelDistance: py.maximum_travel_distance,
    walkingSpeed: py.walking_speed,
    totalExitWidth: py.total_exit_width,
    flowRate: py.flow_rate,
    occupancy: py.occupancy,
    assessmentTime: py.assessment_time,
    referenceHeight: py.reference_height,
    tstep: py.tstep,
  };
}

/** Largest relative difference across a series, falling back to absolute near zero. */
function maxDeviation(expected: number[], actual: number[]): { at: number; rel: number } {
  let worst = { at: -1, rel: 0 };
  for (let i = 0; i < expected.length; i += 1) {
    const e = expected[i];
    const a = actual[i];
    const rel = Math.abs(e) > 1e-12 ? Math.abs((a - e) / e) : Math.abs(a - e);
    if (rel > worst.rel) worst = { at: i, rel };
  }
  return worst;
}

const SERIES: Array<[string, keyof SmokeLayerStep]> = [
  ['clearHeight', 'clearHeight'],
  ['smokeLayerTemp', 'smokeLayerTemp'],
  ['addedSmokeTemp', 'addedSmokeTemp'],
  ['hrr', 'hrr'],
  ['convectiveHrr', 'convectiveHrr'],
  ['depthChange', 'depthChange'],
];

// The port uses Math.cbrt where Python writes ** (1/3). Both are correctly
// rounded to within an ulp, so results agree to floating-point noise rather
// than bit-for-bit; 1e-9 relative is several orders tighter than anything
// that could move a reported number.
const TOLERANCE = 1e-9;

describe.each(caseNames)('parity with warehouse_smoke_layer.py: %s', (name) => {
  const expected = fixture.cases[name];
  const actual = calculateSmokeLayer(toInputs(fixture.inputs[name]));

  it('runs for the same number of timesteps', () => {
    expect(actual.steps.length).toBe(expected.stepCount);
  });

  it('reports the same ASET and whether it was triggered', () => {
    expect(actual.asetTriggered).toBe(expected.asetTriggered);
    expect(actual.aset).toBe(expected.aset);
  });

  it('reports the same RSET and its components', () => {
    expect(actual.rset).toBe(expected.rset);
    expect(actual.queueTime).toBe(expected.queueTime);
    expect(actual.peoplePerSecond).toBeCloseTo(expected.peoplePerSecond, 12);
    expect(actual.totalPreEvac).toBeCloseTo(expected.totalPreEvac, 12);
  });

  it('reports the same reference height breach', () => {
    expect(actual.referenceHeightBreached).toBe(expected.referenceHeightBreached);
    expect(actual.breachTime).toBe(expected.breachTime);
  });

  it.each(SERIES)('matches the Python %s at every timestep', (key, field) => {
    const series = expected.steps[key];
    const ours = actual.steps.map((s) => s[field] as number);
    expect(ours).toHaveLength(series.length);

    const worst = maxDeviation(series, ours);
    if (worst.rel > TOLERANCE) {
      throw new Error(
        `${key} diverged at step ${worst.at} (t=${actual.steps[worst.at]?.time}): ` +
          `python=${series[worst.at]} ts=${ours[worst.at]} rel=${worst.rel}`,
      );
    }
  });

  it('ends at the same clear height', () => {
    expect(actual.finalClearHeight).toBeCloseTo(expected.finalClearHeight, 9);
  });
});
