import { calculateSmokeLayer } from '../../lib/smoke-layer-calc';
import type { SmokeLayerInputs } from '../../lib/smoke-layer-types';

/**
 * Reference values are generated by running the loop from the original
 * Python script (warehouse_smoke_layer.py) unchanged — see
 * app/warehouse-smoke/REFERENCE.md. The port must reproduce them exactly,
 * so tolerances here are tight (1e-9 relative).
 */

const PROJECT_SHED: SmokeLayerInputs = {
  roomArea: 43047,
  rackingPerc: 0.33,
  roomHeight: 15,
  fgr: 0.188,
  detectionTime: 60,
  preMovementTime: 180,
  maximumTravelDistance: 115,
  walkingSpeed: 1.2,
  totalExitWidth: 17,
  flowRate: 1.33,
  occupancy: 1431,
  assessmentTime: 1200,
  referenceHeight: 5.3,
  tstep: 1,
};

const VERIFICATION_SHAFT: SmokeLayerInputs = {
  ...PROJECT_SHED,
  roomArea: 25,
  rackingPerc: 0,
  maximumTravelDistance: 2.5,
  totalExitWidth: 1,
  occupancy: 25 / 30,
  referenceHeight: 2,
};

const NO_BREACH: SmokeLayerInputs = {
  ...PROJECT_SHED,
  rackingPerc: 0,
  fgr: 0.0117,
};

describe('calculateSmokeLayer — RSET', () => {
  it('sums detection, pre-movement, travel and queue time', () => {
    const r = calculateSmokeLayer(PROJECT_SHED);
    expect(r.totalPreEvac).toBeCloseTo(335.83333333333337, 10);
    expect(r.peoplePerSecond).toBeCloseTo(22.61, 10);
    expect(r.queueTime).toBe(64);
    expect(r.rset).toBe(400);
  });

  it('rejects a zero exit width rather than dividing by zero', () => {
    expect(() => calculateSmokeLayer({ ...PROJECT_SHED, totalExitWidth: 0 })).toThrow(
      /exit width/i
    );
  });

  it('rejects a zero room area', () => {
    expect(() => calculateSmokeLayer({ ...PROJECT_SHED, roomArea: 0 })).toThrow(/room area/i);
  });

  it('rejects racking taking up the whole floor plate', () => {
    expect(() => calculateSmokeLayer({ ...PROJECT_SHED, rackingPerc: 1 })).toThrow(/racking/i);
  });
});

describe('calculateSmokeLayer — project shed (2 m never breached)', () => {
  const r = calculateSmokeLayer(PROJECT_SHED);

  it('runs the full assessment time', () => {
    expect(r.steps).toHaveLength(1200);
    expect(r.asetTriggered).toBe(false);
    expect(r.aset).toBe(1200);
  });

  it('breaches the 5.3 m reference height at 1197 s', () => {
    expect(r.referenceHeightBreached).toBe(true);
    expect(r.breachTime).toBe(1197);
  });

  it('matches the Python layer height at sampled timesteps', () => {
    expect(r.steps[0].clearHeight).toBeCloseTo(14.999902765530642, 10);
    expect(r.steps[9].clearHeight).toBeCloseTo(14.997074854726081, 10);
    expect(r.steps[49].clearHeight).toBeCloseTo(14.959306738900159, 10);
    expect(r.steps[99].clearHeight).toBeCloseTo(14.869849147831106, 10);
    expect(r.steps[1199].clearHeight).toBeCloseTo(5.272330349028264, 10);
    expect(r.finalClearHeight).toBeCloseTo(5.272330349028264, 10);
  });

  it('matches the Python layer temperature at sampled timesteps', () => {
    expect(r.steps[0].smokeLayerTemp).toBeCloseTo(20.038655707606836, 10);
    expect(r.steps[49].smokeLayerTemp).toBeCloseTo(24.01865288827281, 10);
    expect(r.steps[1199].smokeLayerTemp).toBeCloseTo(408.2233770078759, 10);
  });

  it('caps the plume temperature at 900 K above ambient', () => {
    expect(r.steps[1199].addedSmokeTemp).toBeCloseTo(920, 10);
    expect(Math.max(...r.steps.map((s) => s.addedSmokeTemp))).toBeCloseTo(920, 10);
  });

  it('matches the Python heat release rate', () => {
    expect(r.steps[99].hrr).toBeCloseTo(1.88, 10);
    expect(r.steps[99].convectiveHrr).toBeCloseTo(1.316, 10);
    expect(r.steps[1199].hrr).toBeCloseTo(270.72, 10);
  });

  it('matches the Python depth change per timestep', () => {
    expect(r.steps[0].depthChange).toBeCloseTo(9.723446935842415e-5, 14);
    expect(r.steps[1199].depthChange).toBeCloseTo(0.007844857640167291, 12);
  });

  it('reports a positive margin of safety when 2 m is never reached', () => {
    expect(r.marginOfSafety).toBe(1200 - 400);
  });
});

describe('calculateSmokeLayer — verification shaft (fast ASET)', () => {
  const r = calculateSmokeLayer(VERIFICATION_SHAFT);

  it('breaches 2 m at 54 s and stops 30 s later', () => {
    expect(r.asetTriggered).toBe(true);
    expect(r.aset).toBe(54);
    expect(r.steps).toHaveLength(84);
    expect(r.breachTime).toBe(54);
  });

  it('matches the Python layer height at sampled timesteps', () => {
    expect(r.steps[0].clearHeight).toBeCloseTo(14.887824520973748, 10);
    expect(r.steps[9].clearHeight).toBeCloseTo(12.113684025836696, 10);
    expect(r.steps[49].clearHeight).toBeCloseTo(2.356134545157005, 10);
    expect(r.steps[83].clearHeight).toBeCloseTo(0.30253117614332403, 10);
  });

  it('reports a negative margin of safety when ASET precedes RSET', () => {
    expect(r.rset).toBe(244);
    expect(r.marginOfSafety).toBe(54 - 244);
  });
});

describe('calculateSmokeLayer — nothing breached', () => {
  const r = calculateSmokeLayer(NO_BREACH);

  it('breaches neither the tenability nor the reference height', () => {
    expect(r.asetTriggered).toBe(false);
    expect(r.referenceHeightBreached).toBe(false);
    expect(r.breachTime).toBeNull();
    expect(r.finalClearHeight).toBeCloseTo(12.83464606689299, 10);
  });
});

describe('calculateSmokeLayer — occupant escape', () => {
  const r = calculateSmokeLayer(PROJECT_SHED);

  it('holds everyone until the pre-evacuation time has elapsed', () => {
    expect(r.steps[100].escaped).toBe(0);
    expect(r.steps[334].escaped).toBe(0);
  });

  it('never lets more people escape than are in the building', () => {
    expect(Math.max(...r.steps.map((s) => s.escaped))).toBe(1431);
  });

  it('clears the building by RSET', () => {
    const atRset = r.steps.find((s) => s.time === r.rset);
    expect(atRset!.escaped).toBe(1431);
  });
});

describe('calculateSmokeLayer — timestep independence', () => {
  it('gives a similar answer at a half-second timestep', () => {
    const coarse = calculateSmokeLayer(VERIFICATION_SHAFT);
    const fine = calculateSmokeLayer({ ...VERIFICATION_SHAFT, tstep: 0.5 });
    expect(fine.aset).toBeGreaterThan(coarse.aset - 5);
    expect(fine.aset).toBeLessThan(coarse.aset + 5);
  });
});
